apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: batch-rs
spec:
  replicas: 3
  selector:
    matchLabels:
      app: batch
  template:
    metadata:
      labels:
        app: batch
    spec:
      containers:
      - name: batch-container
        image: bhagyash654/batch:v2
